/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as donationSol from "./Donation.sol";
export type { donationSol };
export type { PiggyBank } from "./PiggyBank";
export * as factories from "./factories";
export type { DonationApp } from "./Donation.sol/DonationApp";
export { DonationApp__factory } from "./factories/Donation.sol/DonationApp__factory";
export { PiggyBank__factory } from "./factories/PiggyBank__factory";
