/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  VRFConsumerBaseV2Interface,
  VRFConsumerBaseV2InterfaceInterface,
} from "../VRFConsumerBaseV2Interface";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "randomWords",
        type: "uint256[]",
      },
    ],
    name: "fulfillRandomWords",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class VRFConsumerBaseV2Interface__factory {
  static readonly abi = _abi;
  static createInterface(): VRFConsumerBaseV2InterfaceInterface {
    return new Interface(_abi) as VRFConsumerBaseV2InterfaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): VRFConsumerBaseV2Interface {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as VRFConsumerBaseV2Interface;
  }
}
