/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SimpleMultisig } from "./SimpleMultisig";
export * as factories from "./factories";
export { SimpleMultisig__factory } from "./factories/SimpleMultisig__factory";
