/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  VRFCoordinatorV2Interface,
  VRFCoordinatorV2InterfaceInterface,
} from "../VRFCoordinatorV2Interface";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "keyHash",
        type: "bytes32",
      },
      {
        internalType: "uint64",
        name: "subId",
        type: "uint64",
      },
      {
        internalType: "uint16",
        name: "minimumRequestConfirmations",
        type: "uint16",
      },
      {
        internalType: "uint32",
        name: "callbackGasLimit",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "numWords",
        type: "uint32",
      },
    ],
    name: "requestRandomWords",
    outputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class VRFCoordinatorV2Interface__factory {
  static readonly abi = _abi;
  static createInterface(): VRFCoordinatorV2InterfaceInterface {
    return new Interface(_abi) as VRFCoordinatorV2InterfaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): VRFCoordinatorV2Interface {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as VRFCoordinatorV2Interface;
  }
}
